![](../docs/banner.png)

# NumPy


## Exercises

### 1.

Import numpy under the alias `np`.

In [1]:
import numpy as np

### 2.

Create the following arrays:

1. Create an array of 5 zeros.
2. Create an array of 10 ones.
3. Create an array of 5 3.141s.
4. Create an array of the integers 1 to 20.
5. Create a 5 x 5 matrix of ones with a dtype `int`.

In [10]:
np.zeros(5)
np.ones(10)
np.full(5,3.141)
np.arange(1,21)
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 3.

Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [19]:
# Your answer here.
t = np.random.randn(3,3,3)
t.reshape(27,)


array([ 0.19441694,  1.68682395,  1.63893759,  0.2496481 ,  0.36442122,
        0.14046017,  1.06870263, -0.99661591,  1.04300131,  2.04506441,
        0.60801738,  1.26408617, -1.51683826, -0.62293943,  0.94919409,
        1.52285672,  0.29436585,  0.89798413, -0.95764984, -0.64827457,
        0.34285305, -0.77674473, -0.0169466 ,  0.24720324,  1.18533351,
        0.59755874,  0.61067298])

### 4.

Create an array of 20 linearly spaced numbers between 1 and 10.

In [20]:
# Your answer here.
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### 5.

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [22]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

```python
20
```

In [24]:
# Your answer here.
a[3,4]

20

```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [ ]:
# Your answer here.
a[1:,3:]


```python
array([ 6,  7,  8,  9, 10])
```

In [29]:
# Your answer here.
a[1,:]

array([ 6,  7,  8,  9, 10])

```python
array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])
```

In [31]:
# Your answer here.
a[2:4,:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

```python
array([[ 8,  9],
       [13, 14]])
```

In [33]:
# Your answer here.
a[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

### 6.

Calculate the sum of all the numbers in `a`.

In [35]:
# Your answer here.
a.sum()


325

### 7.

Calculate the sum of each row in `a`.

In [38]:
# Your answer here.
a.sum(axis=1)

array([ 15,  40,  65,  90, 115])

### 8.

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [43]:
# Your answer here.
m = a.mean()
z = a[(a > m)]
z

array([14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

### 9.

Find the location of the minimum value in the following array `b`:

In [ ]:
np.random.seed(123)
b = np.random.randn(10)
b

In [48]:
# Your answer here.
b.argmin()


6

### 10.

Find the location of the maximum value in the following 2D array `c` (hint: there are many ways to do this question, but a quick search on stackoverflow.com will typically help you find the optimum solution for a problem, for example see [post](https://stackoverflow.com/questions/3584243/get-the-position-of-the-biggest-item-in-a-multi-dimensional-numpy-array)):

In [ ]:
np.random.seed(123)
c = np.random.randn(3, 2)
c

In [58]:
max = c.max()
max
max_po = c.argmax()
max_po

5

<hr>
<hr>
<hr>